---
- name: Create directories
  file: path=/{{nc_root}} state=directory mode=0755

- name: Create directories
  file: path=/{{nc_root}}/{{nc_path}} state=directory mode=0755

- name: Download owncloud tarball
  get_url: url=https://download.nextcloud.com/server/releases/nextcloud-{{nc_ver}}.tar.bz2 dest=/{{nc_root}}/nextcloud-{{nc_ver}}.tar.bz2 validate_certs=no

- name: Run only if it hasn't been done already
  stat: path=/{{nc_root}}/{{nc_path}}/{{nc_dest}}
  register: st

- name: Extract the Tarball
  shell: tar -xjf nextcloud-{{nc_ver}}.tar.bz2
  args:
    chdir: "/{{nc_root}}"
  when: not st.stat.exists

- name: Copy data to wwwroot
  shell: cp -r /{{nc_root}}/nextcloud /{{nc_root}}/{{nc_path}}/
  when: not st.stat.exists

- name: Remove Documents default user folder
  file: path=/{{nc_root}}/{{nc_path}}/{{nc_dest}}/core/skeleton/Documents state=absent

- name: Remove Photos default user folder
  file: path=/{{nc_root}}/{{nc_path}}/{{nc_dest}}/core/skeleton/Photos state=absent

- name: Remove install directory
  file: path=/{{nc_root}}/nextcloud state=absent
